firmware_build:
  stage: test
  image: antoinealb/gcc-arm-embedded
  before_script:
    - rm -rf ChibiOS
    - git submodule update --init --recursive
    - apt-get update && apt-get install -y python3-pip python-protobuf protobuf-compiler
    - pip3 install PyYAML==3.12 cvra-packager

  script:
    - packager
    - make protoc
    - make
