firmware_tests:
  # TODO cleanup this
  variables:
    CFLAGS: "-std=gnu99"
  stage: test
  image: antoinealb/cpputest
  before_script:
    - rm -rf ChibiOS
    - git submodule update --init --recursive
    - apt-get update && apt-get install -y cmake python3-pip python-protobuf protobuf-compiler
    - pip3 install PyYAML==3.12 cvra-packager

    # Install nanopb
    - pushd lib/nanopb/nanopb/generator/proto
    - make
    - popd

  script:
    - packager
    - make protoc
    - mkdir -p build && pushd build
    - cmake ..
    - make check
    - popd

firmware_build:
  stage: test
  image: antoinealb/gcc-arm-embedded
  before_script:
    - rm -rf ChibiOS
    - git submodule update --init --recursive
    - apt-get update && apt-get install -y python3-pip python-protobuf protobuf-compiler
    - pip3 install PyYAML==3.12 cvra-packager

    # Install nanopb
    - pushd lib/nanopb/nanopb/generator/proto
    - make
    - popd

  script:
    - packager
    - make protoc
    - make


tools-test:
  stage: test
  image: ubuntu:xenial
  before_script:
    - apt-get update && apt-get install -y python3-pip python3-protobuf protobuf-compiler
    - git submodule update --init --recursive
  script:
    - make protoc
    - cd tools
    - python -m unittest discover
