image: ubuntu:xenial
before_script:
  - git submodule update --init --recursive
  - .ci/install_common_dependencies.sh

firmware_tests:
  stage: test
  script:
    - .ci/install_cpputest.sh
    - packager
    - make protoc
    - mkdir -p build && cd build
    - cmake ..
    - make check

firmware_build:
  stage: test
  script:
    - .ci/install_crosscompiler.sh
    - packager
    - make protoc
    - make

tools_tests:
  stage: test
  script:
    - pip3 install protobuf~=3.5.1
    - cd tools
    - python3 -m unittest discover
