before_script:
  - rm -rf ChibiOS
  - git submodule update --init --recursive
  - apt-get update && apt-get install -y cmake python3-pip python-pip wget unzip
  - pip3 install PyYAML==3.12 cvra-packager
  - pip install protobuf
  - pushd /
  - wget https://github.com/google/protobuf/releases/download/v3.5.1/protoc-3.5.1-linux-x86_64.zip
  - unzip protoc*.zip
  - popd

    # Install nanopb
  - pushd lib/nanopb/nanopb/generator/proto
  - make
  - popd

firmware_tests:
  # TODO cleanup this
  variables:
    CFLAGS: "-std=gnu99"
  stage: test
  image: antoinealb/cpputest
  script:
    - packager
    - make protoc
    - mkdir -p build && pushd build
    - cmake ..
    - make check
    - popd

firmware_build:
  stage: test
  image: antoinealb/gcc-arm-embedded
  script:
    - packager
    - make protoc
    - make
