dependency-dir: lib
templates:
  app_src.mk.jinja: app_src.mk
  CMakeLists.txt.jinja: CMakeLists.txt

include_directories:
  - src/
  - src/board/
  - build/ # for generated protobuf messages

depends:
  - lwip
  - lwip_bindings
  - nanopb
  - msgbus
  - parameter

target.arm:
  - src/board/board.c
  - src/cmd.c
  - src/input_mapper_thread.c
  - src/main.c
  - src/mpu9250_thread.c
  - src/parameter_port.c
  - src/sbus_thread.c
  - src/telemetry/rpc_callbacks.c
  - src/telemetry/rpc_server_thread.c
  - src/telemetry/udp_topic_broadcaster.c
  - src/telemetry/udp_topic_injector.c
  - src/usbconf.c

source:
  - src/commander.c
  - src/input_mapper.c
  - src/mpu9250.c
  - src/msgbus_protobuf.c
  - src/sbus.c
  - src/telemetry/rpc.c
  - src/telemetry/rpc_parameter_server.c

tests:
  - tests/arming.cpp
  - tests/hal_mocks.cpp
  - tests/input_remapper.cpp
  - tests/mpu9250.cpp
  - tests/msgbus_protobuf.cpp
  - tests/rpc.cpp
  - tests/rpc_parameter.cpp
  - tests/sbus_parser.cpp
