dependency-dir: lib
templates:
  app_src.mk.jinja: app_src.mk
  CMakeLists.txt.jinja: CMakeLists.txt

include_directories:
  - src/
  - src/board/
  - build/ # for generated protobuf messages

depends:
  - lwip
  - lwip_bindings
  - nanopb
  - msgbus
  - parameter

target.arm:
  - src/main.c
  - src/usbconf.c
  - src/cmd.c
  - src/parameter_port.c
  - src/udp_topic_broadcaster.c
  - src/udp_topic_injector.c
  - src/rpc_server_thread.c
  - src/rpc_callbacks.c
  - src/board/board.c

source:
  - src/msgbus_protobuf.c
  - src/sbus.c
  - src/rpc.c
  - src/rpc_parameter_server.c

tests:
  - tests/msgbus_protobuf.cpp
  - tests/sbus_parser.cpp
  - tests/rpc.cpp
  - tests/rpc_parameter.cpp
