dependency-dir: lib
templates:
  app_src.mk.jinja: app_src.mk
  CMakeLists.txt.jinja: CMakeLists.txt

include_directories:
  - src/
  - src/board/
  - build/ # for generated protobuf messages

depends:
  - lwip
  - lwip_bindings
  - nanopb
  - msgbus
  - parameter
  - madgwick
  - fatfs
  - parameter_flash_storage

target.arm:
  - src/board/board.c
  - src/cmd.c
  - src/commander/commander_thread.cpp
  - src/datalogging/sdcard_logger.c
  - src/exti.c
  - src/fatfs_bindings/fatfs_diskio.c
  - src/fatfs_bindings/fatfs_syscalls.c
  - src/input_mapper/input_mapper_thread.cpp
  - src/ip_uart.c
  - src/log.c
  - src/main.c
  - src/mpu9250_thread.c
  - src/output_mixer/output_pwm_thread.c
  - src/parameter_port.c
  - src/sbus/sbus_thread.c
  - src/sdcard.c
  - src/state_estimation_thread.c
  - src/telemetry/rpc_callbacks.c
  - src/telemetry/rpc_server_thread.c
  - src/telemetry/udp_topic_broadcaster.c
  - src/telemetry/udp_topic_injector.c
  - src/usbconf.c

target.stm32f4: []

source:
  - src/commander/commander.c
  - src/input_mapper/input_mapper.c
  - src/mpu9250.c
  - src/msgbus_protobuf.c
  - src/output_mixer/output_mixer.c
  - src/sbus/sbus.c
  - src/telemetry/rpc.c
  - src/telemetry/rpc_parameter_server.c

tests:
  - src/commander/test_commander.cpp
  - src/input_mapper/test_input_mapper.cpp
  - src/output_mixer/test_output_mixer.cpp
  - src/sbus/sbus_decode_test.cpp
  - src/telemetry/tests/rpc.cpp
  - src/telemetry/tests/rpc_parameter.cpp
  - tests/hal_mocks.cpp
  - tests/mpu9250.cpp
  - tests/msgbus_protobuf.cpp
